### ISSUE TITLE
Add icons for Perplexity and Anyscale

### ISSUE THREAD

**Issue by arunreddy** [abhishekshankr/AIcons#4]
Hi Abhishek,

Thanks for creating the AI icon library. Can you please add Perplexity (https://www.perplexity.ai/) and Anyscale (https://www.anyscale.com/).

**Comment by abhishekshankr** [comment]
The icons have been added to the latest version.

![image](https://github.com/abhishekshankr/AIcons/assets/130513777/0795262d-4991-4626-9e1b-a46b118bd6d3)

**Comment by arunreddy** [comment]
Thanks Abhishek.
